//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Soomla.Store;
using UnityEngine;

namespace light
{
		public class BazaarEvents
		{
				public BazaarEvents ()
				{
					//StoreEvents.OnMarketPurchase+=onMarketPurchase;
				}
			public void onMarketPurchase(PurchasableVirtualItem pvi, string purchaseToken, string payload) {
				#if DEBUG
					//Debug.Log("Just purchased an item with itemId: " + pvi.ItemId);
				#endif
			}
	}
}

